# Generated by Django 4.0.4 on 2022-05-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('descrition', models.TextField()),
            ],
            options={
                'verbose_name': 'category',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('photo', models.FileField(upload_to='dishes/')),
            ],
            options={
                'verbose_name': 'dishes',
                'verbose_name_plural': 'dishes',
                'db_table': 'dishes',
            },
        ),
    ]
