# Generated by Django 4.0.4 on 2022-05-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_visitors_dishes_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitors',
            name='password',
        ),
        migrations.AlterField(
            model_name='visitors',
            name='otp',
            field=models.IntegerField(null=True),
        ),
    ]
