# Generated by Django 4.0.4 on 2022-05-15 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_remove_visitors_password_alter_visitors_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.FileField(null=True, upload_to='category/'),
        ),
    ]
