# Generated by Django 4.0.4 on 2022-05-17 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_order_orderdetail'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orderdetail',
            table='ordersdetails',
        ),
    ]
